#!/usr/bin/env python3

import sys
import rgl_learner.morpho_cats
import rgl_learner.learn_paradigms
import rgl_learner.smart_paradigms
from smart_paradigms import paradigm_guesser, lemma_guesser

if len(sys.argv) == 4 and sys.argv[1] == "morpho-cats":
    rgl_learner.morpho_cats.learn(sys.argv[2],sys.argv[3])
elif len(sys.argv) == 3 and sys.argv[1] == "learn-paradigms":
    rgl_learner.learn_paradigms.learn(sys.argv[2])
elif len(sys.argv) == 3 and sys.argv[1] == "smart-paradigms":
    rgl_learner.smart_paradigms.learn(sys.argv[2])
elif len(sys.argv) == 3 and sys.argv[1] == "learn-smart-par":
    paradigm_guesser.guess_paradigm(sys.argv[2])
elif len(sys.argv) == 5 and sys.argv[1] == "learn-by-lemma":
    lemma_guesser.guess_by_lemma(sys.argv[2], sys.argv[3], sys.argv[4])
else:
    print(f"Synopsis: {sys.argv[0]} morpho-cats <wiktionary|unimorph> <lang-code>")
    print(f"          {sys.argv[0]} learn-paradigms <lang-code>")
    print(f"          {sys.argv[0]} smart-paradigms <lang-code>")
    print(f"          {sys.argv[0]} learn-smart-par <lang-code>")
    print(f"          {sys.argv[0]} learn-by-lemma <lang-code>")
