iso3 = "Mkd"

def patchN(table):
    table.setdefault("indefinite",{}).setdefault("singular","-")
    table.setdefault("indefinite",{}).setdefault("plural","-")
    table.setdefault("definite",{}).setdefault("unspecified",{}).setdefault("singular","-")
    table.setdefault("definite",{}).setdefault("unspecified",{}).setdefault("plural","-")
    table.setdefault("definite",{}).setdefault("proximal",{}).setdefault("singular","-")
    table.setdefault("definite",{}).setdefault("proximal",{}).setdefault("plural","-")
    table.setdefault("definite",{}).setdefault("distal",{}).setdefault("singular","-")
    table.setdefault("definite",{}).setdefault("distal",{}).setdefault("plural","-")
    table.setdefault("vocative",{}).setdefault("singular","-")
    table.setdefault("vocative",{}).setdefault("plural","-")
    table.setdefault("count-form",{}).setdefault("singular","-")
    table.setdefault("count-form",{}).setdefault("plural",table.get("indefinite",{"plural": "-"}).get("plural","-"))
    table.pop("singular",None)
    table.pop("plural",None)
    table.pop("masculine",None)
    table.pop("feminine",None)
    table.pop("augmentative",None)
    table.pop("collective",None)
    table.pop("alternative",None)
    table.pop("general",None)
