params = {"ARGIO3": ("P3", "IOPerson"),
    "ARGABS1": ("P1", "AbsPerson"),
    "ARGABS3": ("P3", "AbsPerson"),
    "PAST": ("Past", "Tense"),
    "ARGIOFEM": ("Fem", "IOGender"),
    "HYP": ("Hyp", "Tense"), # hypothetic
    "ARGERG1": ("P1", "ErgPerson"),
    "ARGABS2": ("P2", "AbsPerson"),
    "ARGERG2": ("P2", "ErgPerson"),
    "ARGIO2": ("P2", "IOPerson"),
    "PRES": ("Pres", "Tense"),
    "ARGIOPL": ("Pl", "IOPerson"),
    "ARGABSPL": ("Pl", "AbsNumber"),
    "ARGABSINFM": ("Informal", "AbsFormality"),
    "ARGERGINFM": ("Informal", "ErgFormality"),
    "ARGIO1": ("P1", "IOPerson"),
    "ARGERGFEM": ("Fem", "ErgGender"),
    "ARGIOINFM": ("Informal", "IOFormality"),
    "ARGERGSG": ("Sg", "ErgNumber"),
    "ARGIOSG": ("Sg", "IONumber"),
    "ARGABSSG": ("Sg", "AbsNumber"),
    "ARGERGPL": ("Pl", "ErgNumber"),
    "ARGERGMASC": ("Masc", "ErgGender"),
    "ARGIOMASC": ("Masc", "IOGender"),
    "ARGERG3": ("P3", "ErgPerson"),}